import pandas as pd
import numpy as np
import json
import os

def compute_global_timestamps(csv_path):
    """
    Applies offline linear regression to map hardware sensor timestamps 
    to the host's time-of-arrival clock, eliminating USB jitter.
    
    Arguments:
    - csv_path (str): The file path to the timestamps.csv generated by the camera.
    
    Returns:
    - pd.DataFrame: The loaded data with a new, sorted 'global_timestamp_ms' column.
    """
    df = pd.read_csv(csv_path)
    sensor_ts = df['sensor_timestamp_ms'].values
    arrival_ts = df['time_of_arrival_ms'].values
    
    slope, intercept = np.polyfit(sensor_ts, arrival_ts, 1)
    df['global_timestamp_ms'] = (sensor_ts * slope) + intercept
    
    # Sort just in case, required for merge_asof
    df = df.sort_values('global_timestamp_ms')
    return df

def format_dropped_ranges(indices):
    """
    Helper function to group consecutive dropped frame indices into readable ranges.
    
    Arguments:
    - indices (list of int): A sorted list of dropped hardware frame indices.
    
    Returns:
    - str: A comma-separated string of ranges (e.g., "1-3, 10, 15-20").
    """
    if not indices: 
        return "None"
    
    ranges = []
    start = indices[0]
    end = indices[0]
    
    for i in range(1, len(indices)):
        if indices[i] == end + 1:
            end = indices[i]
        else:
            ranges.append(str(start) if start == end else f"{start}-{end}")
            start = end = indices[i]
            
    ranges.append(str(start) if start == end else f"{start}-{end}")
    return ", ".join(ranges)

def synchronize_and_clean_jsons(master_cam, camera_csv_paths, camera_json_paths, output_dir, threshold_ms=12.0):
    """
    Aligns YOLO tracking data purely by regression timestamps, discarding the 
    hardware frame indices. Any frames where a camera experienced a blackout 
    (exceeding the threshold) are deleted from ALL cameras to ensure 
    perfect 1:1 triangulation.

    Arguments:
    - master_cam (str): The string key of the flawless camera (e.g., 'realsense').
    - camera_csv_paths (dict): cam_name -> path to timestamps.csv
    - camera_json_paths (dict): cam_name -> path to raw YOLO JSON
    - output_dir (str): Folder to save the cleaned JSONs.
    - threshold_ms (float): Maximum allowed gap between cameras (default 12.0 ms).
    
    Returns:
    - dict: A mapping of cam_name to the file path of its new, synced JSON.
    """
    os.makedirs(output_dir, exist_ok=True)
    cam_names = list(camera_csv_paths.keys())
    
    print("\n[Aligner] Computing global timelines for all cameras...")
    dfs = {}
    for cam in cam_names:
        dfs[cam] = compute_global_timestamps(camera_csv_paths[cam])

    # 1. Start with the Master timeline as the anchor
    df_master = dfs[master_cam][['frame_index', 'global_timestamp_ms']].copy()
    df_master.rename(columns={'frame_index': f'orig_index_{master_cam}'}, inplace=True)
    
    # 2. Asynchronously merge every slave camera onto the Master timeline
    aligned_df = df_master
    for cam in cam_names:
        if cam == master_cam:
            continue
            
        df_slave = dfs[cam][['frame_index', 'global_timestamp_ms']].copy()
        df_slave.rename(columns={'frame_index': f'orig_index_{cam}'}, inplace=True)
        
        # merge_asof pairs rows based on the closest timestamp.
        # If the closest timestamp is further away than the tolerance (blackout), it inserts NaN.
        aligned_df = pd.merge_asof(
            aligned_df, 
            df_slave, 
            on='global_timestamp_ms', 
            direction='nearest', 
            tolerance=threshold_ms
        )

    # 3. Drop any row that contains a NaN (This deletes the blackouts across ALL cameras)
    starting_frames = len(aligned_df)
    aligned_df = aligned_df.dropna().reset_index(drop=True)
    frames_kept = len(aligned_df)
    frames_dropped = starting_frames - frames_kept
    
    print(f"[Aligner] Sync complete. Kept: {frames_kept} frames. Dropped: {frames_dropped} master frames due to slave blackouts.")

    # --- NEW: Auditing dropped hardware frames ---
    print("\n[Aligner] Auditing exact dropped hardware frames per camera:")
    for cam in cam_names:
        # Get the original hardware indices that survived the merge
        surviving_indices = set(aligned_df[f'orig_index_{cam}'].dropna().astype(int))
        all_indices = set(dfs[cam]['frame_index'].astype(int))
        dropped_indices = sorted(list(all_indices - surviving_indices))
        
        dropped_str = format_dropped_ranges(dropped_indices)
        print(f"  -> {cam} lost {len(dropped_indices)} frames. (Indices: {dropped_str})")
    print("-" * 50)
    # ---------------------------------------------

    # 4. Load the raw YOLO JSONs
    print("[Aligner] Loading raw YOLO JSONs...")
    raw_jsons = {}
    for cam in cam_names:
        with open(camera_json_paths[cam], 'r') as f:
            raw_jsons[cam] = json.load(f)

    # 5. Build the new, unified JSON arrays
    print("[Aligner] Building unified JSONs...")
    cleaned_jsons = {cam: [] for cam in cam_names}
    
    for unified_index, row in aligned_df.iterrows():
        for cam in cam_names:
            orig_idx = int(row[f'orig_index_{cam}'])
            original_frame_data = raw_jsons[cam][orig_idx]
            
            # Create a new frame dict with the unified index
            new_frame_data = {
                "frame_index": unified_index,
                "orig_hardware_index": orig_idx, # Kept for debugging/reference
                "detections": original_frame_data.get('detections', [])
            }
            cleaned_jsons[cam].append(new_frame_data)

    # 6. Save the output
    output_paths = {}
    for cam in cam_names:
        out_path = os.path.join(output_dir, f"{cam}_time_synced.json")
        with open(out_path, 'w') as f:
            json.dump(cleaned_jsons[cam], f, indent=4)
        output_paths[cam] = out_path
        print(f"[Aligner] Saved perfectly synced JSON: {out_path}")

    return output_paths

if __name__ == "__main__":
    pass