import numpy as np
import json
import os
from scipy.interpolate import interp1d

def weighted_dlt_triangulate(projection_matrices, points_2d, confidences):
    """
    Calculates the 3D coordinate using a Weighted N-Camera DLT.
    
    Arguments:
    - projection_matrices: List of 3x4 numpy arrays (the P matrices for each valid camera).
    - points_2d: List of [u, v] pixel coordinates corresponding to each valid camera.
    - confidences: List of YOLO confidence scores (used to weight the math).
    
    Returns:
    - A numpy array [X, Y, Z] representing the 3D spatial coordinate.
    """
    A = []
    
    for P, (u, v), weight in zip(projection_matrices, points_2d, confidences):
        # High confidence = strong pull on the 3D point. Low confidence = weak pull.
        row1 = weight * (u * P[2, :] - P[0, :])
        row2 = weight * (v * P[2, :] - P[1, :])
        
        A.append(row1)
        A.append(row2)
        
    A = np.array(A)
    
    # Singular Value Decomposition solves the matrix for the intersection point
    _, _, Vh = np.linalg.svd(A)
    X = Vh[-1, :]
    
    return X[:3] / X[3]


def polish_3d_point(initial_3d_point, projection_matrices, points_2d):
    """
    TODO: The Non-Linear Optimization Step (Levenberg-Marquardt).
    
    Arguments:
    - initial_3d_point: The [X, Y, Z] array generated by the DLT function.
    - projection_matrices: List of 3x4 P matrices.
    - points_2d: List of [u, v] pixel coordinates.
    """
    # Bypassing for now until the SciPy optimizer is implemented
    return initial_3d_point


def interpolate_missing_data(trajectory_3d):
    """
    Fills in missing 3D coordinates (NaNs) across a timeline using cubic spline interpolation.
    
    Arguments:
    - trajectory_3d: A numpy array of shape (num_frames, 3) representing the X, Y, Z timeline of one joint.
    
    Returns:
    - A smoothed numpy array (num_frames, 3) with missing frames mathematically guessed.
    """
    frames = np.arange(len(trajectory_3d))
    valid_mask = ~np.isnan(trajectory_3d[:, 0])
    
    if not np.any(valid_mask):
        return trajectory_3d
        
    smoothed_trajectory = np.empty_like(trajectory_3d)
    
    for axis in range(3):
        valid_frames = frames[valid_mask]
        valid_data = trajectory_3d[valid_mask, axis]
        
        # Extrapolate fills in the gaps if the joint was lost at the very beginning or end
        interpolator = interp1d(valid_frames, valid_data, kind='cubic', fill_value="extrapolate")
        smoothed_trajectory[:, axis] = interpolator(frames)
        
    return smoothed_trajectory


def process_kinematics(camera_json_paths, projection_dict, output_path, confidence_threshold=0.6, min_cameras=2, do_optimization=False):
    """
    The main master function. Parses YOLO JSONs, aligns frames, filters bad views, 
    and runs the 3D triangulation for the entire video.
    
    Arguments:
    - camera_json_paths: Dictionary mapping camera names to their JSON file paths. 
                         (e.g., {'realsense': 'rs_data.json', 'gopro1': 'gp_data.json'})
    - projection_dict: Dictionary mapping camera names to their calculated 3x4 P matrices.
    - output_path: String path to save the final 3D skeleton JSON.
    - confidence_threshold: Float. Minimum YOLO score to include that camera's ray.
    - min_cameras: Integer. Minimum clear views required to attempt DLT math.
    - do_optimization: Boolean. Toggle to activate the future Polish step.
    """
    print("Loading YOLO tracking data...")
    cam_data = {}
    for cam_name, path in camera_json_paths.items():
        with open(path, 'r') as f:
            cam_data[cam_name] = json.load(f)

    # Assumes your frames have been perfectly synced prior to running this script
    num_frames = min(len(data) for data in cam_data.values())
    num_joints = 17 
    
    # Create an empty timeline filled with NaNs
    final_3d_timeline = np.full((num_frames, num_joints, 3), np.nan)

    print(f"Processing {num_frames} synced frames across {len(camera_json_paths)} cameras...")

    for frame_idx in range(num_frames):
        for joint_idx in range(num_joints):
            points_2d = []
            confidences = []
            valid_P = []

            for cam_name in camera_json_paths.keys():
                try:
                    # Extracts the specific frame and the first person detected (pid 0)
                    person_data = cam_data[cam_name][frame_idx]['detections'][0]
                    
                    # Assuming your multi-cam YOLO outputs a 'keypoints_2d' array 
                    # structured as [u, v, confidence]
                    kp = person_data.get('keypoints_2d', person_data.get('keypoints_3d_m', []))[joint_idx]
                    
                    # Ensure the data exists and is valid
                    if kp[0] is not None and kp[1] is not None:
                        u, v, conf = float(kp[0]), float(kp[1]), float(kp[2])
                        
                        if conf >= confidence_threshold:
                            points_2d.append([u, v])
                            confidences.append(conf)
                            valid_P.append(projection_dict[cam_name])
                            
                except (IndexError, KeyError):
                    # Fails safely if YOLO lost the person entirely in this camera
                    continue

            # The Gatekeeper Check
            if len(valid_P) >= min_cameras:
                pt_3d = weighted_dlt_triangulate(valid_P, points_2d, confidences)
                
                if do_optimization:
                    pt_3d = polish_3d_point(pt_3d, valid_P, points_2d)
                    
                final_3d_timeline[frame_idx, joint_idx] = pt_3d

    print("Running cubic spline interpolation to fix occlusions...")
    for joint_idx in range(num_joints):
        final_3d_timeline[:, joint_idx, :] = interpolate_missing_data(final_3d_timeline[:, joint_idx, :])

    print("Saving final 3D skeleton to JSON...")
    output_data = []
    for frame_idx in range(num_frames):
        frame_joints = final_3d_timeline[frame_idx].tolist()
        output_data.append({
            "frame_index": frame_idx,
            "keypoints_3d": frame_joints
        })
        
    with open(output_path, 'w') as f:
        json.dump(output_data, f, indent=4)
        
    print(f"Done! Saved to {output_path}")

if __name__ == "__main__":
    pass